// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/golibs/crypto/random/hashmap (interfaces: Rand)

// Package mock_hashmap is a generated GoMock package.
package mock_hashmap

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRand is a mock of Rand interface.
type MockRand struct {
	ctrl     *gomock.Controller
	recorder *MockRandMockRecorder
}

// MockRandMockRecorder is the mock recorder for MockRand.
type MockRandMockRecorder struct {
	mock *MockRand
}

// NewMockRand creates a new mock instance.
func NewMockRand(ctrl *gomock.Controller) *MockRand {
	mock := &MockRand{ctrl: ctrl}
	mock.recorder = &MockRandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRand) EXPECT() *MockRandMockRecorder {
	return m.recorder
}

// Int mocks base method.
func (m *MockRand) Int() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int")
	ret0, _ := ret[0].(int)
	return ret0
}

// Int indicates an expected call of Int.
func (mr *MockRandMockRecorder) Int() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int", reflect.TypeOf((*MockRand)(nil).Int))
}

// Intn mocks base method.
func (m *MockRand) Intn(arg0 int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Intn", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Intn indicates an expected call of Intn.
func (mr *MockRandMockRecorder) Intn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Intn", reflect.TypeOf((*MockRand)(nil).Intn), arg0)
}
