linters-settings:
  misspell:
    locale: US

linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - exportloopref
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - goheader
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - importas
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goerr113
    - path: os/alias\.go
      linters:
        - gochecknoglobals
      text: IsNotExist is a global variable
    - text: "mnd: Magic number: 0700*"
      linters:
        - gomnd
