// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Gotify is an autogenerated mock type for the Gotify type
type Gotify struct {
	mock.Mock
}

// Notify provides a mock function with given fields: title, priority, content, args
func (_m *Gotify) Notify(title string, priority int, content string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, title, priority, content)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, string, ...interface{}) error); ok {
		r0 = rf(title, priority, content, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Ping provides a mock function with given fields:
func (_m *Gotify) Ping() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
