// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// StreamMerger is an autogenerated mock type for the StreamMerger type
type StreamMerger struct {
	mock.Mock
}

// Add provides a mock function with given fields: name, stream
func (_m *StreamMerger) Add(name string, stream io.ReadCloser) {
	_m.Called(name, stream)
}

// ListenToAll provides a mock function with given fields: ctx, onNewLine
func (_m *StreamMerger) ListenToAll(ctx context.Context, onNewLine func(string)) error {
	ret := _m.Called(ctx, onNewLine)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(string)) error); ok {
		r0 = rf(ctx, onNewLine)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
