// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/golibs/params (interfaces: EnvParams)

// Package mock_params is a generated GoMock package.
package mock_params

import (
	gomock "github.com/golang/mock/gomock"
	logging "github.com/qdm12/golibs/logging"
	params "github.com/qdm12/golibs/params"
	url "net/url"
	reflect "reflect"
	time "time"
)

// MockEnvParams is a mock of EnvParams interface
type MockEnvParams struct {
	ctrl     *gomock.Controller
	recorder *MockEnvParamsMockRecorder
}

// MockEnvParamsMockRecorder is the mock recorder for MockEnvParams
type MockEnvParamsMockRecorder struct {
	mock *MockEnvParams
}

// NewMockEnvParams creates a new mock instance
func NewMockEnvParams(ctrl *gomock.Controller) *MockEnvParams {
	mock := &MockEnvParams{ctrl: ctrl}
	mock.recorder = &MockEnvParamsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEnvParams) EXPECT() *MockEnvParamsMockRecorder {
	return m.recorder
}

// GetDatabaseDetails mocks base method
func (m *MockEnvParams) GetDatabaseDetails() (string, string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseDetails")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(string)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetDatabaseDetails indicates an expected call of GetDatabaseDetails
func (mr *MockEnvParamsMockRecorder) GetDatabaseDetails() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseDetails", reflect.TypeOf((*MockEnvParams)(nil).GetDatabaseDetails))
}

// GetDuration mocks base method
func (m *MockEnvParams) GetDuration(arg0 string, arg1 ...params.GetEnvSetter) (time.Duration, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDuration", varargs...)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDuration indicates an expected call of GetDuration
func (mr *MockEnvParamsMockRecorder) GetDuration(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDuration", reflect.TypeOf((*MockEnvParams)(nil).GetDuration), varargs...)
}

// GetEnv mocks base method
func (m *MockEnvParams) GetEnv(arg0 string, arg1 ...params.GetEnvSetter) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEnv", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnv indicates an expected call of GetEnv
func (mr *MockEnvParamsMockRecorder) GetEnv(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnv", reflect.TypeOf((*MockEnvParams)(nil).GetEnv), varargs...)
}

// GetEnvInt mocks base method
func (m *MockEnvParams) GetEnvInt(arg0 string, arg1 ...params.GetEnvSetter) (int, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEnvInt", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvInt indicates an expected call of GetEnvInt
func (mr *MockEnvParamsMockRecorder) GetEnvInt(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvInt", reflect.TypeOf((*MockEnvParams)(nil).GetEnvInt), varargs...)
}

// GetEnvIntRange mocks base method
func (m *MockEnvParams) GetEnvIntRange(arg0 string, arg1, arg2 int, arg3 ...params.GetEnvSetter) (int, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEnvIntRange", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvIntRange indicates an expected call of GetEnvIntRange
func (mr *MockEnvParamsMockRecorder) GetEnvIntRange(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvIntRange", reflect.TypeOf((*MockEnvParams)(nil).GetEnvIntRange), varargs...)
}

// GetExeDir mocks base method
func (m *MockEnvParams) GetExeDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExeDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExeDir indicates an expected call of GetExeDir
func (mr *MockEnvParamsMockRecorder) GetExeDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExeDir", reflect.TypeOf((*MockEnvParams)(nil).GetExeDir))
}

// GetGotifyToken mocks base method
func (m *MockEnvParams) GetGotifyToken(arg0 ...params.GetEnvSetter) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGotifyToken", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGotifyToken indicates an expected call of GetGotifyToken
func (mr *MockEnvParamsMockRecorder) GetGotifyToken(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGotifyToken", reflect.TypeOf((*MockEnvParams)(nil).GetGotifyToken), arg0...)
}

// GetGotifyURL mocks base method
func (m *MockEnvParams) GetGotifyURL(arg0 ...params.GetEnvSetter) (*url.URL, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGotifyURL", varargs...)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGotifyURL indicates an expected call of GetGotifyURL
func (mr *MockEnvParamsMockRecorder) GetGotifyURL(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGotifyURL", reflect.TypeOf((*MockEnvParams)(nil).GetGotifyURL), arg0...)
}

// GetGroupID mocks base method
func (m *MockEnvParams) GetGroupID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupID")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetGroupID indicates an expected call of GetGroupID
func (mr *MockEnvParamsMockRecorder) GetGroupID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupID", reflect.TypeOf((*MockEnvParams)(nil).GetGroupID))
}

// GetHTTPTimeout mocks base method
func (m *MockEnvParams) GetHTTPTimeout(arg0 ...params.GetEnvSetter) (time.Duration, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetHTTPTimeout", varargs...)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHTTPTimeout indicates an expected call of GetHTTPTimeout
func (mr *MockEnvParamsMockRecorder) GetHTTPTimeout(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHTTPTimeout", reflect.TypeOf((*MockEnvParams)(nil).GetHTTPTimeout), arg0...)
}

// GetListeningPort mocks base method
func (m *MockEnvParams) GetListeningPort(arg0 ...params.GetEnvSetter) (string, string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetListeningPort", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetListeningPort indicates an expected call of GetListeningPort
func (mr *MockEnvParamsMockRecorder) GetListeningPort(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListeningPort", reflect.TypeOf((*MockEnvParams)(nil).GetListeningPort), arg0...)
}

// GetLoggerConfig mocks base method
func (m *MockEnvParams) GetLoggerConfig() (logging.Encoding, logging.Level, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoggerConfig")
	ret0, _ := ret[0].(logging.Encoding)
	ret1, _ := ret[1].(logging.Level)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLoggerConfig indicates an expected call of GetLoggerConfig
func (mr *MockEnvParamsMockRecorder) GetLoggerConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoggerConfig", reflect.TypeOf((*MockEnvParams)(nil).GetLoggerConfig))
}

// GetLoggerEncoding mocks base method
func (m *MockEnvParams) GetLoggerEncoding(arg0 ...params.GetEnvSetter) (logging.Encoding, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLoggerEncoding", varargs...)
	ret0, _ := ret[0].(logging.Encoding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoggerEncoding indicates an expected call of GetLoggerEncoding
func (mr *MockEnvParamsMockRecorder) GetLoggerEncoding(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoggerEncoding", reflect.TypeOf((*MockEnvParams)(nil).GetLoggerEncoding), arg0...)
}

// GetLoggerLevel mocks base method
func (m *MockEnvParams) GetLoggerLevel(arg0 ...params.GetEnvSetter) (logging.Level, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLoggerLevel", varargs...)
	ret0, _ := ret[0].(logging.Level)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoggerLevel indicates an expected call of GetLoggerLevel
func (mr *MockEnvParamsMockRecorder) GetLoggerLevel(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoggerLevel", reflect.TypeOf((*MockEnvParams)(nil).GetLoggerLevel), arg0...)
}

// GetOnOff mocks base method
func (m *MockEnvParams) GetOnOff(arg0 string, arg1 ...params.GetEnvSetter) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOnOff", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnOff indicates an expected call of GetOnOff
func (mr *MockEnvParamsMockRecorder) GetOnOff(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnOff", reflect.TypeOf((*MockEnvParams)(nil).GetOnOff), varargs...)
}

// GetPath mocks base method
func (m *MockEnvParams) GetPath(arg0 string, arg1 ...params.GetEnvSetter) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPath", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPath indicates an expected call of GetPath
func (mr *MockEnvParamsMockRecorder) GetPath(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPath", reflect.TypeOf((*MockEnvParams)(nil).GetPath), varargs...)
}

// GetRedisDetails mocks base method
func (m *MockEnvParams) GetRedisDetails() (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRedisDetails")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetRedisDetails indicates an expected call of GetRedisDetails
func (mr *MockEnvParamsMockRecorder) GetRedisDetails() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedisDetails", reflect.TypeOf((*MockEnvParams)(nil).GetRedisDetails))
}

// GetRootURL mocks base method
func (m *MockEnvParams) GetRootURL(arg0 ...params.GetEnvSetter) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRootURL", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRootURL indicates an expected call of GetRootURL
func (mr *MockEnvParamsMockRecorder) GetRootURL(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRootURL", reflect.TypeOf((*MockEnvParams)(nil).GetRootURL), arg0...)
}

// GetURL mocks base method
func (m *MockEnvParams) GetURL(arg0 string, arg1 ...params.GetEnvSetter) (*url.URL, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetURL", varargs...)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL
func (mr *MockEnvParamsMockRecorder) GetURL(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockEnvParams)(nil).GetURL), varargs...)
}

// GetUserID mocks base method
func (m *MockEnvParams) GetUserID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetUserID indicates an expected call of GetUserID
func (mr *MockEnvParamsMockRecorder) GetUserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockEnvParams)(nil).GetUserID))
}

// GetValueIfInside mocks base method
func (m *MockEnvParams) GetValueIfInside(arg0 string, arg1 []string, arg2 ...params.GetEnvSetter) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetValueIfInside", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValueIfInside indicates an expected call of GetValueIfInside
func (mr *MockEnvParamsMockRecorder) GetValueIfInside(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueIfInside", reflect.TypeOf((*MockEnvParams)(nil).GetValueIfInside), varargs...)
}

// GetYesNo mocks base method
func (m *MockEnvParams) GetYesNo(arg0 string, arg1 ...params.GetEnvSetter) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetYesNo", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetYesNo indicates an expected call of GetYesNo
func (mr *MockEnvParamsMockRecorder) GetYesNo(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetYesNo", reflect.TypeOf((*MockEnvParams)(nil).GetYesNo), varargs...)
}
