// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/golibs/params (interfaces: OS)

// Package mock_params is a generated GoMock package.
package mock_params

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOS is a mock of OS interface.
type MockOS struct {
	ctrl     *gomock.Controller
	recorder *MockOSMockRecorder
}

// MockOSMockRecorder is the mock recorder for MockOS.
type MockOSMockRecorder struct {
	mock *MockOS
}

// NewMockOS creates a new mock instance.
func NewMockOS(ctrl *gomock.Controller) *MockOS {
	mock := &MockOS{ctrl: ctrl}
	mock.recorder = &MockOSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOS) EXPECT() *MockOSMockRecorder {
	return m.recorder
}

// ExeDir mocks base method.
func (m *MockOS) ExeDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExeDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExeDir indicates an expected call of ExeDir.
func (mr *MockOSMockRecorder) ExeDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExeDir", reflect.TypeOf((*MockOS)(nil).ExeDir))
}

// GID mocks base method.
func (m *MockOS) GID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GID")
	ret0, _ := ret[0].(int)
	return ret0
}

// GID indicates an expected call of GID.
func (mr *MockOSMockRecorder) GID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GID", reflect.TypeOf((*MockOS)(nil).GID))
}

// UID mocks base method.
func (m *MockOS) UID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UID")
	ret0, _ := ret[0].(int)
	return ret0
}

// UID indicates an expected call of UID.
func (mr *MockOSMockRecorder) UID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UID", reflect.TypeOf((*MockOS)(nil).UID))
}
